In [92]:
import pandas as pd
import matplotlib.pyplot as plt

In [54]:
data = pd.read_csv('BANKNIFTY.csv')

In [55]:
data

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-07-02 00:00:00+05:30,26364.449219,26371.599609,26060.599609,26230.300781,26230.300781,0
1,2018-07-03 00:00:00+05:30,26210.099609,26316.099609,26142.000000,26204.099609,26204.099609,0
2,2018-07-04 00:00:00+05:30,26249.250000,26480.500000,26132.900391,26433.949219,26433.949219,0
3,2018-07-05 00:00:00+05:30,26481.550781,26598.449219,26415.199219,26503.300781,26503.300781,0
4,2018-07-06 00:00:00+05:30,26427.550781,26609.849609,26410.000000,26493.849609,26493.849609,0
...,...,...,...,...,...,...,...
748,2021-07-23 00:00:00+05:30,34748.351562,35088.000000,34404.750000,35034.398438,35034.398438,0
749,2021-07-26 00:00:00+05:30,34947.851562,35138.199219,34669.550781,34949.699219,34949.699219,0
750,2021-07-27 00:00:00+05:30,35029.300781,35186.101562,34713.550781,34797.449219,34797.449219,0
751,2021-07-28 00:00:00+05:30,34839.449219,34841.550781,34115.199219,34532.898438,34532.898438,0
752,2021-07-29 00:00:00+05:30,34740.300781,34778.148438,34495.199219,34691.500000,34691.500000,0

In [81]:
Gapup = []
Gapdown = []

for i in range(len(data)-1):
    if(data.Open[i+1] - data.High[i]>0):
        Gapup.append([(data.Open[i+1] - data.High[i])/data.Close[i],data.Date[i+1]])
    elif(data.Low[i]-data.Open[i+1]>0):
        Gapdown.append([(data.Low[i] - data.Open[i+1])/data.Close[i],data.Date[i+1]])

[[3.975120180887179e-05, '2018-07-05 00:00:00+05:30'],
 [0.0012266997993564397, '2018-07-09 00:00:00+05:30'],
 [0.0023679905151890576, '2018-07-10 00:00:00+05:30'],
 [0.002443711366389148, '2018-07-18 00:00:00+05:30'],
 [0.001558072978077301, '2018-07-27 00:00:00+05:30'],
 [0.0038574967384189755, '2018-07-30 00:00:00+05:30'],
 [0.0016808066743694823, '2018-08-06 00:00:00+05:30'],
 [0.0016035663761640995, '2018-08-09 00:00:00+05:30'],
 [0.0005662133342825516, '2018-08-23 00:00:00+05:30'],
 [0.0021989085961356537, '2018-08-28 00:00:00+05:30'],
 [0.0015002488930661844, '2018-09-03 00:00:00+05:30'],
 [0.006141093826353118, '2018-09-14 00:00:00+05:30'],
 [0.004664380572989463, '2018-09-26 00:00:00+05:30'],
 [0.002495551004769184, '2018-10-12 00:00:00+05:30'],
 [0.005160243540231299, '2018-10-17 00:00:00+05:30'],
 [0.00822575333250804, '2018-10-22 00:00:00+05:30'],
 [0.007532285188661818, '2018-10-24 00:00:00+05:30'],
 [0.0033354909405345235, '2018-11-01 00:00:00+05:30'],
 [0.005676511789675366, '2018-11-02 00:00:00+05:30'],
 [0.006050014086457423, '2018-11-14 00:00:00+05:30'],
 [0.00029631328917309474, '2018-11-16 00:00:00+05:30'],
 [0.0012135241374989004, '2018-11-19 00:00:00+05:30'],
 [0.0021411482105670333, '2018-11-29 00:00:00+05:30'],
 [0.000206045424968689, '2018-11-30 00:00:00+05:30'],
 [0.0007520087132093388, '2018-12-03 00:00:00+05:30'],
 [0.002230199763938487, '2018-12-12 00:00:00+05:30'],
 [0.006434924922210662, '2018-12-13 00:00:00+05:30'],
 [0.00024040925780958772, '2018-12-17 00:00:00+05:30'],
 [0.0006991797718552255, '2018-12-19 00:00:00+05:30'],
 [0.0063549585365878375, '2018-12-27 00:00:00+05:30'],
 [0.0020037257721126993, '2018-12-31 00:00:00+05:30'],
 [0.0003865951024671182, '2019-01-02 00:00:00+05:30'],
 [0.003829762479316051, '2019-01-07 00:00:00+05:30'],
 [0.003956800718842582, '2019-01-09 00:00:00+05:30'],
 [0.0005039208610444799, '2019-01-17 00:00:00+05:30'],
 [0.0017273058754345, '2019-01-30 00:00:00+05:30'],
 [0.0019720188113921456, '2019-01-31 00:00:00+05:30'],
 [0.00034804336517290903, '2019-02-01 00:00:00+05:30'],
 [0.0003431581680918551, '2019-02-21 00:00:00+05:30'],
 [0.0007652137447727831, '2019-03-01 00:00:00+05:30'],
 [0.0013555033948190183, '2019-03-06 00:00:00+05:30'],
 [0.0010355956454891578, '2019-03-11 00:00:00+05:30'],
 [0.004741347552277842, '2019-03-12 00:00:00+05:30'],
 [0.003503673938359411, '2019-03-14 00:00:00+05:30'],
 [3.0644867729172756e-05, '2019-03-18 00:00:00+05:30'],
 [0.0011916916010555395, '2019-03-22 00:00:00+05:30'],
 [0.0028110426760436067, '2019-03-27 00:00:00+05:30'],
 [0.0013658144595662292, '2019-04-01 00:00:00+05:30'],
 [0.0009140874048039319, '2019-04-08 00:00:00+05:30'],
 [0.002429902443176628, '2019-04-16 00:00:00+05:30'],
 [0.00214699913658163, '2019-04-18 00:00:00+05:30'],
 [0.000408601630089615, '2019-04-25 00:00:00+05:30'],
 [0.02278260596212734, '2019-05-20 00:00:00+05:30'],
 [0.0011134699255811462, '2019-05-21 00:00:00+05:30'],
 [0.00942454382745899, '2019-05-23 00:00:00+05:30'],
 [0.0003333827668017169, '2019-05-28 00:00:00+05:30'],
 [0.0018914355271677486, '2019-05-31 00:00:00+05:30'],
 [0.003849787194501924, '2019-06-10 00:00:00+05:30'],
 [0.00014818513968798845, '2019-07-04 00:00:00+05:30'],
 [8.952828133550253e-05, '2019-07-12 00:00:00+05:30'],
 [0.0070195225246117866, '2019-07-29 00:00:00+05:30'],
 [0.002442166259627377, '2019-08-09 00:00:00+05:30'],
 [0.0028741400352624304, '2019-08-19 00:00:00+05:30'],
 [0.016938846377072412, '2019-08-26 00:00:00+05:30'],
 [0.003973002477588886, '2019-08-27 00:00:00+05:30'],
 [0.0026722753772959276, '2019-09-11 00:00:00+05:30'],
 [0.001481498253267924, '2019-09-12 00:00:00+05:30'],
 [0.021408487646437786, '2019-09-23 00:00:00+05:30'],
 [0.005726255784205149, '2019-10-22 00:00:00+05:30'],
 [0.0025683810867329587, '2019-10-29 00:00:00+05:30'],
 [0.0002694344204727793, '2019-10-30 00:00:00+05:30'],
 [0.0005852699041267195, '2019-10-31 00:00:00+05:30'],
 [0.00022750627493602071, '2019-11-04 00:00:00+05:30'],
 [0.0007709871960485231, '2019-11-07 00:00:00+05:30'],
 [0.004006548791302628, '2019-11-15 00:00:00+05:30'],
 [0.0032085916974842698, '2019-11-26 00:00:00+05:30'],
 [0.0020359687818120122, '2019-11-28 00:00:00+05:30'],
 [0.00206542293409763, '2019-12-05 00:00:00+05:30'],
 [0.0006063065377878378, '2019-12-12 00:00:00+05:30'],
 [0.002024337695548739, '2019-12-13 00:00:00+05:30'],
 [0.001685162661939605, '2019-12-16 00:00:00+05:30'],
 [0.0024548779373215826, '2019-12-18 00:00:00+05:30'],
 [0.0012880892777956511, '2019-12-30 00:00:00+05:30'],
 [0.009447430787766083, '2020-01-09 00:00:00+05:30'],
 [0.001339881077034094, '2020-01-10 00:00:00+05:30'],
 [0.004760852835895807, '2020-01-20 00:00:00+05:30'],
 [0.0013377969901989418, '2020-01-31 00:00:00+05:30'],
 [0.004313323840690132, '2020-02-04 00:00:00+05:30'],
 [0.0001580671779836424, '2020-02-06 00:00:00+05:30'],
 [0.00694478527607362, '2020-02-19 00:00:00+05:30'],
 [0.004696870493008235, '2020-03-02 00:00:00+05:30'],
 [0.002253680871179496, '2020-03-26 00:00:00+05:30'],
 [0.01999857204268696, '2020-03-27 00:00:00+05:30'],
 [0.007446746595933123, '2020-04-07 00:00:00+05:30'],
 [0.010739882395576765, '2020-04-15 00:00:00+05:30'],
 [0.04507470199742268, '2020-04-17 00:00:00+05:30'],
 [0.011515074934114982, '2020-04-20 00:00:00+05:30'],
 [0.0032991826294862265, '2020-04-23 00:00:00+05:30'],
 [0.010549674956565397, '2020-04-28 00:00:00+05:30'],
 [0.011429423953032094, '2020-04-30 00:00:00+05:30'],
 [0.004450589300268683, '2020-05-08 00:00:00+05:30'],
 [0.05430513578743104, '2020-05-13 00:00:00+05:30'],
 [0.0026829364531751284, '2020-05-28 00:00:00+05:30'],
 [0.01921774394667634, '2020-06-01 00:00:00+05:30'],
 [0.017089440079790994, '2020-06-03 00:00:00+05:30'],
 [0.020794427755592003, '2020-06-08 00:00:00+05:30'],
 [0.0014965565369889672, '2020-06-16 00:00:00+05:30'],
 [0.001120080563055355, '2020-06-22 00:00:00+05:30'],
 [0.007053650605646903, '2020-06-24 00:00:00+05:30'],
 [0.0014670585240468548, '2020-06-26 00:00:00+05:30'],
 [0.003944473055854675, '2020-06-30 00:00:00+05:30'],
 [0.0032852164548580224, '2020-07-02 00:00:00+05:30'],
 [0.006436292351678685, '2020-07-06 00:00:00+05:30'],
 [0.0011667133915944847, '2020-07-08 00:00:00+05:30'],
 [0.011030317234761762, '2020-07-20 00:00:00+05:30'],
 [0.005349036603797061, '2020-07-21 00:00:00+05:30'],
 [0.013040980132341323, '2020-07-22 00:00:00+05:30'],
 [0.005141806844884949, '2020-08-05 00:00:00+05:30'],
 [0.0017307341465937298, '2020-08-10 00:00:00+05:30'],
 [0.0030833829275961192, '2020-08-13 00:00:00+05:30'],
 [0.003953451515489747, '2020-08-19 00:00:00+05:30'],
 [0.005036436459080386, '2020-08-21 00:00:00+05:30'],
 [0.0041614571449967355, '2020-08-24 00:00:00+05:30'],
 [0.003324153226689441, '2020-08-25 00:00:00+05:30'],
 [0.0024792147526666096, '2020-08-27 00:00:00+05:30'],
 [0.01741165669256572, '2020-08-31 00:00:00+05:30'],
 [0.002513136291013329, '2020-09-03 00:00:00+05:30'],
 [0.0006494502826911552, '2020-09-14 00:00:00+05:30'],
 [0.004182086450451332, '2020-09-28 00:00:00+05:30'],
 [0.002864036428884632, '2020-09-29 00:00:00+05:30'],
 [0.006335150694844419, '2020-10-01 00:00:00+05:30'],
 [0.0026229258911714464, '2020-10-05 00:00:00+05:30'],
 [0.0049663300951915375, '2020-10-08 00:00:00+05:30'],
 [0.0021596188298974197, '2020-10-12 00:00:00+05:30'],
 [0.010908020433854228, '2020-10-19 00:00:00+05:30'],
 [0.0013696570000968859, '2020-10-21 00:00:00+05:30'],
 [0.00377600837311552, '2020-11-02 00:00:00+05:30'],
 [0.011012152351876562, '2020-11-05 00:00:00+05:30'],
 [0.00878765798157606, '2020-11-09 00:00:00+05:30'],
 [0.016141774202003353, '2020-11-10 00:00:00+05:30'],
 [0.009544793425310808, '2020-11-17 00:00:00+05:30'],
 [0.0008927884286496101, '2020-11-23 00:00:00+05:30'],
 [0.006527153969348208, '2020-11-25 00:00:00+05:30'],
 [0.004321353386851069, '2020-12-01 00:00:00+05:30'],
 [0.003730729221886113, '2020-12-16 00:00:00+05:30'],
 [0.0043586215911504715, '2020-12-24 00:00:00+05:30'],
 [0.0004276006451527522, '2020-12-28 00:00:00+05:30'],
 [0.002520959081391579, '2020-12-29 00:00:00+05:30'],
 [0.003845515903104797, '2020-12-30 00:00:00+05:30'],
 [0.0024197245313575884, '2021-01-04 00:00:00+05:30'],
 [0.002279120432031145, '2021-01-06 00:00:00+05:30'],
 [0.004638671050227188, '2021-01-07 00:00:00+05:30'],
 [0.003775516041588434, '2021-01-08 00:00:00+05:30'],
 [0.00459662916679551, '2021-01-13 00:00:00+05:30'],
 [0.003851792067564922, '2021-01-21 00:00:00+05:30'],
 [0.007782056107234881, '2021-01-29 00:00:00+05:30'],
 [0.008575344209051403, '2021-02-02 00:00:00+05:30'],
 [0.006275343935950622, '2021-02-05 00:00:00+05:30'],
 [0.0049460843165606465, '2021-02-15 00:00:00+05:30'],
 [0.001144664097838834, '2021-02-16 00:00:00+05:30'],
 [0.005363173127896484, '2021-02-25 00:00:00+05:30'],
 [0.0002088791735442947, '2021-03-03 00:00:00+05:30'],
 [0.0009605073447934926, '2021-03-10 00:00:00+05:30'],
 [0.008916757833113501, '2021-03-12 00:00:00+05:30'],
 [0.0016633823101096128, '2021-03-26 00:00:00+05:30'],
 [0.00015757154117277544, '2021-03-30 00:00:00+05:30'],
 [0.0013738807979979664, '2021-04-15 00:00:00+05:30'],
 [0.008480038521279045, '2021-04-20 00:00:00+05:30'],
 [0.005303839754884582, '2021-04-26 00:00:00+05:30'],
 [0.0017839564323234051, '2021-04-28 00:00:00+05:30'],
 [0.0036741415564418406, '2021-04-29 00:00:00+05:30'],
 [0.0013491381301833471, '2021-05-04 00:00:00+05:30'],
 [0.0011774620747472752, '2021-05-06 00:00:00+05:30'],
 [0.0025983121918029413, '2021-05-07 00:00:00+05:30'],
 [0.011542491986520917, '2021-05-18 00:00:00+05:30'],
 [0.005052506014538738, '2021-05-24 00:00:00+05:30'],
 [0.0035574148910108294, '2021-05-28 00:00:00+05:30'],
 [0.0015607782098429194, '2021-06-01 00:00:00+05:30'],
 [0.0034092414926322483, '2021-06-03 00:00:00+05:30'],
 [0.0045258916158814055, '2021-06-11 00:00:00+05:30'],
 [0.0012275137431692095, '2021-06-15 00:00:00+05:30'],
 [0.004509438893215936, '2021-06-22 00:00:00+05:30'],
 [0.0033467492072455146, '2021-07-05 00:00:00+05:30'],
 [0.00170653652942684, '2021-07-12 00:00:00+05:30'],
 [0.002436155783461796, '2021-07-13 00:00:00+05:30']]

In [113]:
x = []
y=[]
for i in Gapup:
    x.append(i[0])
    if(float(i[0])>0.01):
        print((i[1]))
        
for i in Gapdown:
    y.append(i[0])

2019-05-20 00:00:00+05:30
2019-08-26 00:00:00+05:30
2019-09-23 00:00:00+05:30
2020-03-27 00:00:00+05:30
2020-04-15 00:00:00+05:30
2020-04-17 00:00:00+05:30
2020-04-20 00:00:00+05:30
2020-04-28 00:00:00+05:30
2020-04-30 00:00:00+05:30
2020-05-13 00:00:00+05:30
2020-06-01 00:00:00+05:30
2020-06-03 00:00:00+05:30
2020-06-08 00:00:00+05:30
2020-07-20 00:00:00+05:30
2020-07-22 00:00:00+05:30
2020-08-31 00:00:00+05:30
2020-10-19 00:00:00+05:30
2020-11-05 00:00:00+05:30
2020-11-10 00:00:00+05:30
2021-05-18 00:00:00+05:30

In [66]:
Gapdown = np.array(Gapdown)
Gapdown[(Gapdown>0.01)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [134]:
for i in range(len(y)):
    if(y[i]>0.02):
        y[i] =0.021

for i in range(len(x)):
    if(x[i]>0.02):
        x[i] =0.021
        


fig, ax = plt.subplots(1, 1)

y=np.array(y)
ax.hist(x,color='g',rwidth=0.5,orientation='horizontal',bins=4,label=['okay','s','r','ww'])
ax.hist(-y,color='r',rwidth=0.5,orientation='horizontal',bins=4,label='notokay')

rects = ax.patches
labels = ['0.02+','0.015 - 0.02','0.01 - 0.015','0.005 - 0.01','0.0 - 0.01','0.015 - 0.02','0.01 - 0.015','0.005 - 0.01','0.0 - 0.01']

for rect, label in zip(rects, labels):
#     height = 
    ax.text(rect.get_width(),rect.get_height(), label)


plt.show()

In [98]:
%matplotlib

Using matplotlib backend: MacOSX